// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Welcome;

#nullable disable

namespace Welcome.Migrations
{
    [DbContext(typeof(HospitalContext))]
    partial class HospitalContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Welcome.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartmentName = "surgery"
                        },
                        new
                        {
                            Id = 2,
                            DepartmentName = "herapy"
                        },
                        new
                        {
                            Id = 3,
                            DepartmentName = "pediatrics"
                        },
                        new
                        {
                            Id = 4,
                            DepartmentName = "nevrology"
                        },
                        new
                        {
                            Id = 5,
                            DepartmentName = "psychology"
                        });
                });

            modelBuilder.Entity("Welcome.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartmentId = 1,
                            FullName = "Nameness Name Namenneess",
                            Salary = 555555m
                        },
                        new
                        {
                            Id = 2,
                            DepartmentId = 2,
                            FullName = "Fameless Fame Famelllesss",
                            Salary = 58436534m
                        },
                        new
                        {
                            Id = 3,
                            DepartmentId = 3,
                            FullName = "FullNameless FullName FullNameless",
                            Salary = 5321313m
                        },
                        new
                        {
                            Id = 4,
                            DepartmentId = 1,
                            FullName = "Unbeliveable Believe Incredibility",
                            Salary = 76887635m
                        },
                        new
                        {
                            Id = 5,
                            DepartmentId = 5,
                            FullName = "Loveless Love Lonely",
                            Salary = 87687865m
                        });
                });

            modelBuilder.Entity("Welcome.Doctor", b =>
                {
                    b.HasOne("Welcome.Department", "Department")
                        .WithMany("Doctors")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Welcome.Department", b =>
                {
                    b.Navigation("Doctors");
                });
#pragma warning restore 612, 618
        }
    }
}
